# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add Environment File
      run: echo "${{ secrets.PROD_ENV }}" > $GITHUB_WORKSPACE/.env
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install Node
      run: npm install
    - name: Build
      run: npm run build
    - name: Run Lint Checks
      run: npm run lint
    - name: Execute Unit Tests
      run: npm run test
